name: Generate README.

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    - name: Run Python script
      run: |
        python generate.py
    # - name: Upload README.md
    #   uses: actions/upload-artifact@v2
    #   with: 
    #     name: readme
    #     path: README.md
    - name: Commit README
      run: |
        git config --global user.name 'Ohidur Rahman Bappy'
        git config --global user.email 'ohidurbappy@users.noreply.github.com'
        git add README.md
        git commit -am "Automated README"
        git push
